title: Bernette Chan Portfolio
description: My personal website
# theme: jekyll-theme-primer
theme: jekyll-theme-minimal


# naviagation tabs
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
